"""initial schema

Revision ID: 7bf7892874c3
Revises: 
Create Date: 2026-09-09 14:02:43.286354

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7bf7892874c3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service_catalog',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('service_code', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('provisionable', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("provider IN ('aws','azure','gcp')", name='ck_service_catalog_provider'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'service_code', name='uq_service_catalog_provider_service_code')
    )
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('normalized_email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('affiliation_type', sa.String(length=20), nullable=False),
    sa.Column('affiliation_name', sa.String(length=200), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='active', nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('withdrawn_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("affiliation_type IN ('company','individual')", name='ck_users_affiliation_type'),
    sa.CheckConstraint("status IN ('active','withdrawn')", name='ck_users_status'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('normalized_email')
    )
    op.create_table('cloud_accounts',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('external_account_id', sa.String(length=255), nullable=False),
    sa.Column('account_label', sa.String(length=200), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("provider IN ('aws','azure','gcp')", name='ck_cloud_accounts_provider'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'provider', 'external_account_id', name='uq_cloud_accounts_user_provider_external')
    )
    op.create_index(op.f('ix_cloud_accounts_user_id'), 'cloud_accounts', ['user_id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('type', sa.String(length=100), nullable=False),
    sa.Column('reference_type', sa.String(length=100), nullable=True),
    sa.Column('reference_id', sa.BigInteger(), nullable=True),
    sa.Column('message_key', sa.String(length=255), nullable=False),
    sa.Column('message_params', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('is_read', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('password_reset_tokens',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index(op.f('ix_password_reset_tokens_user_id'), 'password_reset_tokens', ['user_id'], unique=False)
    op.create_table('resource_sync_jobs',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.String(length=30), server_default='pending', nullable=False),
    sa.Column('requested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('pending','running','success','partial_success','failed','cancelled')", name='ck_resource_sync_jobs_status'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resource_sync_jobs_user_id'), 'resource_sync_jobs', ['user_id'], unique=False)
    op.create_table('social_accounts',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('provider_user_id', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'provider_user_id', name='uq_social_accounts_provider_provider_user_id'),
    sa.UniqueConstraint('user_id', 'provider', name='uq_social_accounts_user_id_provider')
    )
    op.create_index(op.f('ix_social_accounts_user_id'), 'social_accounts', ['user_id'], unique=False)
    op.create_table('credentials',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('cloud_account_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('encrypted_payload', sa.LargeBinary(), nullable=False),
    sa.Column('encryption_nonce', sa.LargeBinary(), nullable=False),
    sa.Column('encryption_key_version', sa.String(length=50), nullable=False),
    sa.Column('public_identifier', sa.String(length=255), nullable=True),
    sa.Column('permission_scope', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('verified', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('display_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('display_order >= 0', name='ck_credentials_display_order_non_negative'),
    sa.ForeignKeyConstraint(['cloud_account_id'], ['cloud_accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cloud_account_id', 'name', name='uq_credentials_cloud_account_name')
    )
    op.create_index(op.f('ix_credentials_cloud_account_id'), 'credentials', ['cloud_account_id'], unique=False)
    op.create_table('provisioning_jobs',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('credential_id', sa.BigInteger(), nullable=False),
    sa.Column('service_catalog_id', sa.BigInteger(), nullable=False),
    sa.Column('workspace_name', sa.String(length=255), nullable=False),
    sa.Column('idempotency_key', sa.String(length=255), nullable=False),
    sa.Column('spec_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=30), server_default='queued', nullable=False),
    sa.Column('result_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_code', sa.String(length=100), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('queued','running','success','failed','cancelled')", name='ck_provisioning_jobs_status'),
    sa.CheckConstraint('finished_at IS NULL OR started_at IS NULL OR finished_at >= started_at', name='ck_provisioning_jobs_finished_after_started'),
    sa.ForeignKeyConstraint(['credential_id'], ['credentials.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['service_catalog_id'], ['service_catalog.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'idempotency_key', name='uq_provisioning_jobs_user_idempotency'),
    sa.UniqueConstraint('user_id', 'workspace_name', name='uq_provisioning_jobs_user_workspace')
    )
    op.create_index(op.f('ix_provisioning_jobs_credential_id'), 'provisioning_jobs', ['credential_id'], unique=False)
    op.create_index(op.f('ix_provisioning_jobs_service_catalog_id'), 'provisioning_jobs', ['service_catalog_id'], unique=False)
    op.create_index(op.f('ix_provisioning_jobs_user_id'), 'provisioning_jobs', ['user_id'], unique=False)
    op.create_table('resource_sync_job_items',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('sync_job_id', sa.BigInteger(), nullable=False),
    sa.Column('cloud_account_id', sa.BigInteger(), nullable=False),
    sa.Column('credential_id', sa.BigInteger(), nullable=True),
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=30), server_default='pending', nullable=False),
    sa.Column('resources_discovered', sa.Integer(), server_default='0', nullable=False),
    sa.Column('resources_created', sa.Integer(), server_default='0', nullable=False),
    sa.Column('resources_updated', sa.Integer(), server_default='0', nullable=False),
    sa.Column('resources_marked_stale', sa.Integer(), server_default='0', nullable=False),
    sa.Column('error_code', sa.String(length=100), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("provider IN ('aws','azure','gcp')", name='ck_resource_sync_job_items_provider'),
    sa.CheckConstraint("status IN ('pending','running','success','failed','cancelled')", name='ck_resource_sync_job_items_status'),
    sa.CheckConstraint('resources_created >= 0', name='ck_rsji_created_non_negative'),
    sa.CheckConstraint('resources_discovered >= 0', name='ck_rsji_discovered_non_negative'),
    sa.CheckConstraint('resources_marked_stale >= 0', name='ck_rsji_marked_stale_non_negative'),
    sa.CheckConstraint('resources_updated >= 0', name='ck_rsji_updated_non_negative'),
    sa.ForeignKeyConstraint(['cloud_account_id'], ['cloud_accounts.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['credential_id'], ['credentials.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sync_job_id'], ['resource_sync_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sync_job_id', 'cloud_account_id', name='uq_rsji_sync_job_cloud_account')
    )
    op.create_index(op.f('ix_resource_sync_job_items_cloud_account_id'), 'resource_sync_job_items', ['cloud_account_id'], unique=False)
    op.create_index(op.f('ix_resource_sync_job_items_credential_id'), 'resource_sync_job_items', ['credential_id'], unique=False)
    op.create_index(op.f('ix_resource_sync_job_items_sync_job_id'), 'resource_sync_job_items', ['sync_job_id'], unique=False)
    op.create_table('resources',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('cloud_account_id', sa.BigInteger(), nullable=False),
    sa.Column('service_catalog_id', sa.BigInteger(), nullable=False),
    sa.Column('first_collected_by_credential_id', sa.BigInteger(), nullable=True),
    sa.Column('last_collected_by_credential_id', sa.BigInteger(), nullable=True),
    sa.Column('provider_resource_key', sa.String(length=1024), nullable=False),
    sa.Column('external_resource_id', sa.String(length=512), nullable=False),
    sa.Column('original_resource_type', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=512), nullable=True),
    sa.Column('region', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=100), nullable=True),
    sa.Column('estimated_monthly_cost', sa.Numeric(precision=19, scale=6), nullable=True),
    sa.Column('collected_cost_amount', sa.Numeric(precision=19, scale=6), nullable=True),
    sa.Column('cost_currency', sa.CHAR(length=3), nullable=True),
    sa.Column('cost_period_start', sa.Date(), nullable=True),
    sa.Column('cost_period_end', sa.Date(), nullable=True),
    sa.Column('cost_as_of', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cost_source', sa.String(length=100), nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('raw_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_stale', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('collected_cost_amount IS NULL OR collected_cost_amount >= 0', name='ck_resources_collected_cost_non_negative'),
    sa.CheckConstraint('estimated_monthly_cost IS NULL OR estimated_monthly_cost >= 0', name='ck_resources_estimated_cost_non_negative'),
    sa.ForeignKeyConstraint(['cloud_account_id'], ['cloud_accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['first_collected_by_credential_id'], ['credentials.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['last_collected_by_credential_id'], ['credentials.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['service_catalog_id'], ['service_catalog.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cloud_account_id', 'provider_resource_key', name='uq_resources_cloud_account_provider_key')
    )
    op.create_index(op.f('ix_resources_cloud_account_id'), 'resources', ['cloud_account_id'], unique=False)
    op.create_index('ix_resources_cloud_account_service', 'resources', ['cloud_account_id', 'service_catalog_id'], unique=False)
    op.create_index('ix_resources_cloud_account_status', 'resources', ['cloud_account_id', 'status'], unique=False)
    op.create_index(op.f('ix_resources_first_collected_by_credential_id'), 'resources', ['first_collected_by_credential_id'], unique=False)
    op.create_index(op.f('ix_resources_last_collected_by_credential_id'), 'resources', ['last_collected_by_credential_id'], unique=False)
    op.create_index('ix_resources_last_synced_at', 'resources', ['last_synced_at'], unique=False)
    op.create_index('ix_resources_region', 'resources', ['region'], unique=False)
    op.create_index(op.f('ix_resources_service_catalog_id'), 'resources', ['service_catalog_id'], unique=False)
    op.create_index('ix_resources_tags_gin', 'resources', ['tags'], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_resources_tags_gin', table_name='resources', postgresql_using='gin')
    op.drop_index(op.f('ix_resources_service_catalog_id'), table_name='resources')
    op.drop_index('ix_resources_region', table_name='resources')
    op.drop_index('ix_resources_last_synced_at', table_name='resources')
    op.drop_index(op.f('ix_resources_last_collected_by_credential_id'), table_name='resources')
    op.drop_index(op.f('ix_resources_first_collected_by_credential_id'), table_name='resources')
    op.drop_index('ix_resources_cloud_account_status', table_name='resources')
    op.drop_index('ix_resources_cloud_account_service', table_name='resources')
    op.drop_index(op.f('ix_resources_cloud_account_id'), table_name='resources')
    op.drop_table('resources')
    op.drop_index(op.f('ix_resource_sync_job_items_sync_job_id'), table_name='resource_sync_job_items')
    op.drop_index(op.f('ix_resource_sync_job_items_credential_id'), table_name='resource_sync_job_items')
    op.drop_index(op.f('ix_resource_sync_job_items_cloud_account_id'), table_name='resource_sync_job_items')
    op.drop_table('resource_sync_job_items')
    op.drop_index(op.f('ix_provisioning_jobs_user_id'), table_name='provisioning_jobs')
    op.drop_index(op.f('ix_provisioning_jobs_service_catalog_id'), table_name='provisioning_jobs')
    op.drop_index(op.f('ix_provisioning_jobs_credential_id'), table_name='provisioning_jobs')
    op.drop_table('provisioning_jobs')
    op.drop_index(op.f('ix_credentials_cloud_account_id'), table_name='credentials')
    op.drop_table('credentials')
    op.drop_index(op.f('ix_social_accounts_user_id'), table_name='social_accounts')
    op.drop_table('social_accounts')
    op.drop_index(op.f('ix_resource_sync_jobs_user_id'), table_name='resource_sync_jobs')
    op.drop_table('resource_sync_jobs')
    op.drop_index(op.f('ix_password_reset_tokens_user_id'), table_name='password_reset_tokens')
    op.drop_table('password_reset_tokens')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_cloud_accounts_user_id'), table_name='cloud_accounts')
    op.drop_table('cloud_accounts')
    op.drop_table('users')
    op.drop_table('service_catalog')
    # ### end Alembic commands ###
